data_settings:
    root_dir_hyperion : "/mnt/data/course/psarin/inm706/aclImdb"
    root_dir_local: "aclImdb"
    mode: "local"
    stage: "train"
    folder: "all"
model:
  embedding_dim: 256
  hidden_dim: 512
train:
    epochs: 20
    batch_size: 64
