
# Model parameters
batch_size: 32
sequence_length: 64

# Optimized Training parameters
num_epochs: 25
learning_rate: 0.001

# Output settings
checkpoint_dir: 'checkpoints'
output_dir: 'outputs/visualizations'
